### ISSUE TITLE
Dino troubles

### ISSUE THREAD

**Issue by Jessica-Lee123** [Jessica-Lee123/dinosaur-designs#1]
@hellachella
@carolsinc 
Markbot has issues...

**Comment by carolsinc** [comment]
can you post a screen shot of what market is saying?

**Comment by Jessica-Lee123** [comment]
<img width="800" alt="Screen Shot 2021-03-12 at 2 47 32 PM" src="https://user-images.githubusercontent.com/77642609/110990853-e26f7400-8341-11eb-9f7e-8f9e227c8864.png">

**Comment by Jessica-Lee123** [comment]
@carolsinc please let me know if you can see the screen shot. :)

**Comment by carolsinc** [comment]
Yes we are all good!

**Comment by carolsinc** [comment]
for the Dinos r us, go to the zoom chat, and copy and paste that line. 
You misspelled descendants. 
You have an extra <! on your first line of html

**Comment by carolsinc** [comment]
line 23 the id should be inside the < > with the h2

**Comment by Jessica-Lee123** [comment]
Hahaha, figures, me and spelling mistakes go hand-in-hand, thanks so much for checking it over Carol :)

**Comment by Jessica-Lee123** [comment]
@raven-rhea Sorry, just trying to find the lab link. I have 4 issues still and my background colour isn't showing. :( I'll be on soon!

**Comment by Jessica-Lee123** [comment]
@raven-rhea I am failing at this link search though, all i'm finding are the weekly links with Chelle. My bad :(

**Comment by raven-rhea** [comment]
Hey I'm here to help Are you still having issues with your diosaur-designs?

**Comment by raven-rhea** [comment]
I don't have a zoom meeting or anything. I just took a look at your code for this one one thing, you have your <figure> around all three img's and captions each one should be wrapped individually

**Comment by raven-rhea** [comment]
sorry I'm talking about the figure tag

**Comment by raven-rhea** [comment]
<figure>
      <img src="images/hadrosaur.jpg" alt="">
      <figcaption class="intro">Hadrosaurids are descendants of the Upper Jurassic/Lower Cretaceous iguanodontian dinosaurs and had a similar body layout.</figcaption>
    </figure>
    
    Should look like that

**Comment by Jessica-Lee123** [comment]
Thanks so much for your help @raven-rhea :)

**Comment by carolsinc** [comment]
Are you still having issues or did you get through this assignment?

**Comment by Jessica-Lee123** [comment]
@carolsinc Not yet, I am still struggling and my other classes are overwhelming me, I can barely catch up. Is there a Thursday or a weekend I can hire you ( I can retransfer you) to help me with this one and the last one? I am struggling so hard...Just name your price, I think I need at least an hour, maybe two of your time.

**Comment by hellachella** [comment]
pls contact me for some office time.
